ci(release): fixing remaining issues & finalizing in pipeline (#580)
The primary goal of this change is to make semantic releasing process working once and for all!

The remaining observed issue was the following one when executing the command `git commit --message='docs(changelog): release v3.0.3' "${CHANGELOG_FILE}"`:

```
error: pathspec '/home/runner/work/mc-jobs-reborn-patch-place-break/mc-jobs-reborn-patch-place-break/docs/CHANGELOG.md' did not match any file(s) known to git
```

Which gets solved by executing this command before committing:

```
git add "${CHANGELOG_FILE}"
```

Tests outcomes in an ad-hoc repository can be found:
* Successful release workflow: https://github.com/Djaytan/semantic-release-experimentations/actions/runs/7921110356
* Created GitHub release containing both the artifact & the associated signature files: https://github.com/Djaytan/semantic-release-experimentations/releases/tag/v1.10.0
* The opened PR for updating the existing `CHANGELOG.md` file: https://github.com/Djaytan/semantic-release-experimentations/pull/4

Meaning that everything seems good now, and providing us enough confidence concerning the merging outcomes of this change!

Opportunities to finalize the setup has been taken as well:
* Each provided GitHub permission is now justified by a comment
* The `semantic-release-github-pullrequest` dependency has been cleaned-up from the `package.json` file and its `package-lock.json` one
* The `--ci` argument has been removed when dispatching the `semantic-release` command since that's already the default command behavior
* Documenting the hack implemented with the temporary file for retrieving the release version tag name after the `semantic-release` command successful execution
* The `semantic-release` config (i.e. `release.config.js` file) has been simplified:
  * Getting rid of the `releaseRules` property in order to follow standards (i.e. bumping version only for `fix`, `feat` and `BREAKING CHANGE` types)
  * Documenting where Conventional Changelog config specifications can be found for later references
  * Making most of the properties as global ones for improving readability
  * Removing the asset label "Spigot plugin for Minecraft servers" since I prefer having the raw file naming being displayed in the GitHub release instead
  * Relying on the default value of the `releasedLabels` property (hence the removal from the config)